analyzer:
  errors:
    todo: ignore
  exclude:
    - lib/generated/**
    - lib/app/app.router.dart
    

linter:
  rules:
    avoid_void_async: true
    omit_local_variable_types: false
    prefer_single_quotes: false # Let's get back to this eventually
    avoid_unnecessary_containers: true
    prefer_relative_imports: true
    always_declare_return_types: true
    avoid_print: false #use debugPrint()
    unnecessary_new: true 
    sort_constructors_first: false
    sort_pub_dependencies: false
    file_names: true
    lines_longer_than_80_chars: false